### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by sajalsat** [NihalSaran-GL/Amazon-clone#12]
It is only for homepage

**Comment by sajalsat** [comment]
@NihalSaran-GL first fill the cards and add the 3 sliders below that and also add one route, in which if you click on the card it will navigate to the page productdetails/product.jsx

**Comment by sajalsat** [comment]
@NakiShik first complete the footer

**Comment by sajalsat** [comment]
@NihalSaran-GL @NakiShik first synk fork and git pull then do any code

**Comment by NihalSaran-GL** [comment]
Dont use issues because it will potray as if we have issues in our repo
